AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'

# Don't prefer fail to raise.
Style/SignalException:
  Enabled: false

# Don't enforce parentheses for method arguments.
Style/MethodDefParentheses:
  Enabled: false

# Don't enforce DateTime.zone.now.
Rails/TimeZone:
  Enabled: false
